services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - travel_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d travel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  travel_pgdata: